name: seversoftapp
description: Website Development • Cross-Platform Mobile App Development • Graphics • Videos and Animations  VTU Services- Cheap Internet Data • Airtime • Cable Subscription• Electricity Bill • Examination-Pin etc


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.4
  animated_notch_bottom_bar: ^0.0.6
  connectivity_plus: ^2.3.0
  get: ^4.6.5
  flutter_svg:
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter_svg_provider: ^1.0.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_native_splash: "^1.2.0"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/error.html

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

  

flutter_native_splash:

  color: "#FFFFFF"
  image: assets/icons/icon.png

